<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IKHEAKC" failures="0" tests="1" name="testCaseRepo.TC_004" time="34.074" errors="1" timestamp="2025-03-22T23:18:46 IST" skipped="0">
  <testcase classname="testCaseRepo.TC_004" name="CON_001" time="34.074">
    <error message="Can&#039;t open workbook - unsupported file type: PNG" type="java.io.IOException">
      <![CDATA[java.io.IOException: Can't open workbook - unsupported file type: PNG
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:228)
at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:185)
at genericUtility.ExcelUtility.getDataFromExcelFile(ExcelUtility.java:35)
at testCaseRepo.TC_004.CON_001(TC_004.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </error>
    <system-out>
      <![CDATA[CON_001->On Test start
CON_001->On Test failure]]>
    </system-out>
  </testcase> <!-- CON_001 -->
  <system-out>
    <![CDATA[LE_003->On Test start
LE_002->On Test start
LE_002->On Test failure
LE_003->On Test failure
CON_001->On Test start
LE_001->On Test start
LE_001->On Test failure
CON_001->On Test failure
CON_002->On Test start
CON_003->On Test start
CON_003->On Test failure
CON_002->On Test failure]]>
  </system-out>
</testsuite> <!-- testCaseRepo.TC_004 -->
